FILES:
  train_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\random_mixed_ramp\csv\mixed_ramp_0_globally_normalized.csv
  val_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\random_mixed_ramp\csv\mixed_ramp_medium_0_globally_normalized.csv
LEARNING:
  bsz: 64
  e: 200
  p: 8
OPTIMIZER:
  lr: 0.001
  weight_decay: 0.1
STRUCTURE:
  hlszs:
  - 15
  mu: 5
  my: 5
activation: LeakyReLU
