FILES:
  train_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\rnnmpc_random_walk\csv\random_walk_150k_fast_globally_normalized.csv
  val_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\rnnmpc_random_walk\csv\random_walk_30k_fast_globally_normalized.csv
activation: LeakyReLU
bsz: 64
e: 200
hlszs:
- 10
lr: 0.001
mu: 15
my: 0
p: 4
weight_decay: 0.1
