# System parameters
n_MV: 2
n_CV: 2

# Horizons (current OCP-formulation demands these be equal)
H: [50,100,150]

# Tuning parameters
Q: [[1,1], [1000,1], [1,1000]]
R: [[1,1], [1000,1], [1,1000]]
rho: [[1000,1000]]

# Constraints
ylb: [0,0]
yub: [16000,500]
ulb: [0, 0]
uub: [100, 10000]
dulb: [-0.55,-166.7]
duub: [0.55,166.7]
elb: [0,0]
eub: [1000000, 1000000]

# Running parameters
delta_t: 10
warm_start_t: 2000
final_t: 2000

# These are layered, because they should be parsed as dicts
PLUGIN_OPTIONS:
  expand: True
  
SOLVER_OPTIONS: # https://coin-or.github.io/Ipopt/OPTIONS.html
  max_iter: 3000 # default
  tol: 1 # 7000 # 1e8
  dual_inf_tol: 1 # 7000 # 1e8
  constr_viol_tol: 1 # 7000 # 1e8
  compl_inf_tol: 1 # 7000 # 1e8
  acceptable_tol: 1 # 7000 # 1e8
  acceptable_iter: 5