# System parameters
n_MV: 2
n_CV: 2

# Horizons (current OCP-formulation demands these be equal)
H: [80] # Try with different horizons once a good tuning is in place (it's not so mystical; longer is better)

# Tuning parameters
Q: [[1,1000],[1,100]]
R: [[1,6400],[1,25600],[6400,6400],[6400,25600]]
rho: [1000000000,1000000000]

# Constraints
ylb: [0,0]
yub: [18537,349]
ulb: [0, 0]
uub: [100, 10000]
dulb: [-0.55,-333.3]
duub: [0.55,333.3]
elb: [0,0]
eub: [1000000, 1000000]

# Running parameters
delta_t: 10
warm_start_t: 2000
final_t: 3000

# These are layered, because they should be parsed as dicts
PLUGIN_OPTIONS:
  expand: True
  
SOLVER_OPTIONS: # https://coin-or.github.io/Ipopt/OPTIONS.html
  max_iter: 3000 # default
  tol: 1 # 7000 # 1e8
  dual_inf_tol: 1 # 7000 # 1e8
  constr_viol_tol: 1 # 7000 # 1e8
  compl_inf_tol: 1 # 7000 # 1e8
  acceptable_tol: 1 # 7000 # 1e8
  acceptable_iter: 5
  
NORMALIZATION_VALUES:
  choke: [0,100]     # Externally defined hard limits
  GL: [0,10000]      # Externally defined hard limits
  gasrate: [0,18537] # Investigated max (and rounded up) from '/inputs/div/ramp_choke_and_gl'
  oilrate: [0,349]   # Investigated max (and rounded up) from '/inputs/div/ramp_choke_and_gl'