# Config file for values in "src/MPC_basis.py"
#
SYSTEM_PARAMETERS: 
  n_MV: 2
  n_CV: 2

TUNING_PARAMETERS:
  #! Horizon and tuning values are tentative and should be tuned properly
  # Horizons
  Hu: 50
  Hp: 50

  # Tuning parameters
  Q: [1,1]
  P: [1,1]
  rho: [1000,1000]

  # Constraints
  ylb: [0,0]
  yub: [16000,500]
  ulb: [0, 0]
  uub: [100, 10000]
  dulb: [-0.55,-166.7]
  duub: [0.55,166.7]
  elb: [0,0]
  eub: [1000000, 1000000]

RUNNING_PARAMETERS:
  delta_t: 10
  final_time: 20000 #20000