SYSTEM_PARAMETERS: 
  n_MV: 2
  n_CV: 2
  mu: 1
  my: 3

PLUGIN_OPTIONS: 
  expand: True
  
SOLVER_OPTIONS: # https://coin-or.github.io/Ipopt/OPTIONS.html
  max_iter: 10000
  tol: 1000000 # 1e6
  acceptable_tol: 1000000
  acceptable_iter: 1000000

TUNING_PARAMETERS:
  #! Horizon values are tentative and should be tuned properly
  # Horizons (current OCP-formulation demands these be equal)
  Hu: 50
  Hp: 50

  #! Tuning parameters are tentative and should be tuned properly
  # Tuning parameters
  Q: [1,1]
  R: [1,1]
  rho: [1000,1000]

  # Constraints
  ylb: [0,0]
  yub: [16000,500]
  ulb: [0, 0]
  uub: [100, 10000]
  dulb: [-0.55,-166.7]
  duub: [0.55,166.7]
  elb: [0,0]
  eub: [1000000, 1000000]

RUNNING_PARAMETERS:
  delta_t: 10
  warm_start_t: 2000
  final_t: 200