STRUCTURE: 
  mu: 100          # history of inputs considered
  my: 100          # history of outputs considered
  hlszs: [16,16,16]  # sizes of only hidden layers (input and output layers' sizes are implicit from other factors)

LEARNING:
  bsz: 100        # batch size
  e: 500          # epochs
  lr: 0.001       # learning rate
  p: 5            # patience