STRUCTURE: 
  mu: 50          # history of inputs considered
  my: 50          # history of outputs considered
  hlszs: [100]  # sizes of only hidden layers (input and output layers' sizes are implicit from other factors)

LEARNING:
  bsz: 100        # batch size
  e: 500          # epochs
  lr: 0.001       # learning rate
  p: 5            # patience