FILES:
  train_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\random_mixed_ramp\csv\mixed_ramp_0_globally_normalized.csv
  val_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\random_mixed_ramp\csv\mixed_ramp_medium_0_globally_normalized.csv
LEARNING:
  bsz: 64
  e: 100
  p: 5
OPTIMIZER:
  lr: 0.001
  weight_decay: 0.1
STRUCTURE:
  hlszs:
  - 200
  mu: 45
  my: 45
activation: LeakyReLU
