FILES:
  train_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\rnnmpc_random_walk\csv\random_walk_1mill_globally_normalized.csv
  val_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\rnnmpc_random_walk\csv\random_walk_200k_globally_normalized.csv
LEARNING:
  bsz: 64
  e: 200
  p: 5
OPTIMIZER:
  lr: 0.001
  weight_decay: 0.2
STRUCTURE:
  hlszs:
  - 80
  mu: 30
  my: 30
activation: LeakyReLU
