# Config file for values in "src/MPC_basis.py"
#
SYSTEM_PARAMETERS: 
  n_MV: 2
  n_CV: 2

TUNING_PARAMETERS:
  Hu: 80 #200
  Hp: 100 #250
  Hw: 1

  P_bar: [0.1, 1]
  Q_bar: [0.01, 1000]
  rho_h: [10000, 10000]
  rho_l: [10, 10]
  z_bar_lb: [-0.55, -166.7, 0] # = [deltaU_lb, epsilon_h, epsilon_l] # Epsilon bounds come from (4.1b) in Kufoalor
  z_bar_ub: [0.55, 166.7, 1000]
  y_over_bar: [16000, 500]
  y_under_bar: [0, 0]
  u_over_bar: [100, 10000]
  u_under_bar: [0, 0]
  du_over_bar: [0.55, 166.7]
  du_under_bar: [-0.55, -166.7]
  e_over_bar: 1000000
  e_under_bar: 0


SET_POINTS:
  ref: [11500, 280]


RUNNING_PARAMETERS:
  delta_t: 10
  final_time: 4000 #20000