# System parameters
n_MV: 2
n_CV: 2

# Horizons (vals argued for in grid1/verdict.txt)
Hu: 100
Hp: 120 
Hw: 0

# Tuning parameters
R_bar: [[1,6000],[1,8000],[1,10000]]
Q_bar: [[50,8000],[50,10000],[50,12000],[200,8000],[200,10000],[200,12000]]

# # Must be array-nested (like above) if to be grid searched over
rho_h: [10000, 10000]
rho_l: [10000, 10000]

# Constraints
z_bar_lb: [-0.55, -333.3, 0] # = [deltaU_lb, epsilon_h, epsilon_l] # Epsilon bounds come from (4.1b) in Kufoalor
z_bar_ub: [0.55, 333.3, 1000]
y_over_bar: [18537, 349]
y_under_bar: [0, 0]
u_over_bar: [100, 10000]
u_under_bar: [0, 0]
du_over_bar: [0.55, 333.3]
du_under_bar: [-0.55, -333.3]
e_over_bar: 1000000
e_under_bar: 0

# Running parameters
delta_t: 10
final_time: 100 # 25000
warm_start_t: 2000