# TODO: Make so that only 1 layer (I think necessary for grid search)

# Config file for values in "src/MPC_basis.py"
#
# System parameters 
n_MV: 2
n_CV: 2

# Horizons (vals argued for in grid1/verdict.txt)
Hu: 100
Hp: 120
Hw: 0

# Tuning parameters
R_bar: [0.1, 1]
Q_bar: [0.01, 1000]
rho_h: [10000, 10000]
rho_l: [10000, 10000] # [10, 10]

# Constraints # TODO: z_bar_lb and z_bar_ub are obsolete?
z_bar_lb: [-0.55, -333.3, 0] # = [deltaU_lb, epsilon_h, epsilon_l] # Epsilon bounds come from (4.1b) in Kufoalor
z_bar_ub: [0.55, 333.3, 1000]
y_over_bar: [16000, 500]
y_under_bar: [0, 0]
u_over_bar: [100, 10000]
u_under_bar: [0, 0]
du_over_bar: [0.55, 333.3]
du_under_bar: [-0.55, -333.3]
e_over_bar: 1000000
e_under_bar: 0

# Running parameters
delta_t: 10
final_time: 20000
warm_start_t: 2000