FILES:
  train_file: c:\Users\Ynque\Desktop\Uni\'22-'23\masteroppgave\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\staircases\csv\staircases_100_steps_output_clipped.csv
  val_file: c:\Users\Ynque\Desktop\Uni\'22-'23\masteroppgave\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\staircases\csv\staircases_100_steps_output_clipped.csv
LEARNING:
  bsz: 100
  e: 500
  lr: 0.001
  p: 5
STRUCTURE:
  hlszs:
  - 32
  mu: 1
  my: 3
