FILES:
  train_file: c:\Users\Ynque\Desktop\Uni\'22-'23\masteroppgave\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\rnnmpc_random_walk\csv\random_walk_1mill_globally_normalized.csv
  val_file: c:\Users\Ynque\Desktop\Uni\'22-'23\masteroppgave\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\rnnmpc_random_walk\csv\random_walk_200k_globally_normalized.csv
LEARNING:
  bsz: 64
  e: 200
  p: 5
OPTIMIZER:
  lr: 0.001
  weight_decay: 0.2
STRUCTURE:
  hlszs:
  - 50
  mu: 25
  my: 25
activation: LeakyReLU
