FILES:
  train_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\random_mixed_ramp\csv\mixed_ramp_0_globally_normalized.csv
  val_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\random_mixed_ramp\csv\mixed_ramp_medium_0_globally_normalized.csv
LEARNING:
  bsz: 64
  e: 500
  lr: 0.001
  p: 8
STRUCTURE:
  hlszs:
  - 100
  mu: 30
  my: 30
activation: LeakyReLU
