FILES:
  train_file: c:\Users\Ynque\Desktop\Uni\'22-'23\masteroppgave\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\random_choke\csv\random_choke_2_output_clipped.csv
  val_file: c:\Users\Ynque\Desktop\Uni\'22-'23\masteroppgave\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\steps\csv\steps20k_output_clipped.csv
LEARNING:
  bsz: 100
  e: 500
  lr: 0.001
  p: 20
STRUCTURE:
  hlszs:
  - 32
  mu: 5
  my: 5
