# Config file for neural network model approximation of the SingleWell model
#
STRUCTURE:
  n_MV: 2
  n_CV: 2
  mu: 0 # size of history of inputs used in model
  my: 1 # size of history of outputs used in model
  hlszs: 16 # sizes of hidden layers

TRAINING:
  lr: 0.001 # learning rate
  bsz: 100 # batch size
  e: 500 # number of epochs

EVALUATION:
  val_sz: 0.2
  