FILES:
  train_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\random_choke\csv\random_choke_4_output_clipped.csv
  val_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\random_choke\csv\random_choke_1_output_clipped.csv
LEARNING:
  bsz: 100
  e: 500
  lr: 0.001
  p: 5
STRUCTURE:
  hlszs:
  - 32
  mu: 1
  my: 3
