FILES:
  train_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\rnnmpc_random_walk\csv\random_walk_200k_fast_globally_normalized.csv
  val_file: c:\Users\yngveki\Documents\Master\prosjektkode\TTK4900_NNMPC\RNNMPC\generate_data\outputs\rnnmpc_random_walk\csv\random_walk_30k_fast_globally_normalized.csv
activation: LeakyReLU
bsz: 64
e: 200
hlszs:
- 40
lr: 0.001
mu: 5
my: 5
p: 5
weight_decay: 0.1
